apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ajfg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ajfg
    app.kubernetes.io/part-of: cmp-test-file-sample-go-basic-1
  name: devfile-sample-ajfg
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-ajfg
status:
  loadBalancer: {}
